## 50 0
#string "Hello, World!"
#file <file.extension>
# 1 2 3 4 5

-> -> <- <-

<< >>

+1 +2 -3 -4 ~5 ~6

<= => <> 
<% %> <%> 

[]+1
[](+2 -3)
[5]+4
[6](-7 +8)
[-1]-1
[-1](-4+5)
[][]+1

{}+1
{}[]+1

?+1
?(+1 +2)
??+1
??(+1 +2)
???+1
????+1
!?+1
!?(+1 +2)
!??+1
!??(+1 +2)

@thing1
^thing1

&test+1
&thing(+1 +1)
&add<a, b>()
&void<>()

var := 3
what := ^^here

var += $var
var -= ^^there

*test
*thing
*add<$var, |^^myCell|>
*void<>

sum := {+|1, 2, 3}
